name: Publish Branch

on:
    push:
        branches:
            - main

jobs:
    release_candidate:
        runs-on: ubuntu-latest
        env:
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  registry-url: "https://registry.npmjs.org"

            - name: Get current package.json version
              run: echo "PACKAGE_VERSION=$(npm pkg get version | tr -d '"')" >> $GITHUB_ENV

            # get the sort SHA and add it into the environment variables
            - name: Get short SHA
              run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

            - name: Setup Branch Release Candidate Version
              run: echo "NEW_VERSION=$PACKAGE_VERSION-$BRANCH_NAME.$SHORT_SHA" >> $GITHUB_ENV

            - name: Update Package.json Version with Release Candidate Version
              run: echo "npm version $NEW_VERSION"