name: Publish Branch

on:
    push:
        branches:
            - main

jobs:
    publish-branch:
        runs-on: ubuntu-latest
        env:
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  registry-url: "https://registry.npmjs.org"

            - name: Get current package.json version
              run: echo "PACKAGE_VERSION=$(npm pkg get version | tr -d '"')" >> $GITHUB_ENV

            - name: Setup Branch Release Candidate Version
              run: echo "BRANCH_VERSION=$PACKAGE_VERSION-$BRANCH_NAME.${GITHUB_SHA::7}" >> $GITHUB_ENV

            - name: Echo New version
              run: echo "$BRANCH_VERSION"

            - name: Bump version
              run: npm version $BRANCH_VERSION